### ISSUE TITLE
Longitudinal analysis

### ISSUE THREAD

**Issue by AlessandroLazzaro** [FrederickHuangLin/ANCOM-BC-Code-Archive#1]
Dear Developers,
first thank you for this cool implementation of ANCOM.
In the article "Analysis of compositions of microbiomes with bias correction" (DOI: 10.1038/s41467-020-17041-7) I read that "because of the regression framework adopted in ANCOM-BC, it can be extended to more general settings involving multigroup comparisons, adjusting covariates as well as applying to longitudinal/repeated measurements data".
I was wondering how to perform a longitudinal compositional analysis with two time points across two study groups (diseases versus healthy control), also adjusting for covariate as age, gender, etc.
Thanks to the documentation I found on Github, I have been able to perform only a cross-sectional analysis between the two groups (actually I did it twice, once for each time point).
How can I adjust the linear regression that is built in ANCOM-BC to run a longitudinal analysis? Also, how to do it whether the between-groups are more than 2 ? 
Thank you in advance,
Alessandro Lazzaro

**Comment by FrederickHuangLin** [comment]
Hi Alessandro,

Sorry for the terrible delay in responding to your question, for some reason I did not get notifications for this GitHub repo.

Please note that the ANCOMBC package has been accepted on Bioconductor and added to its nightly builds. Please go to its [R package repository](https://github.com/FrederickHuangLin/ANCOMBC) for more details, and I also actively maintain and answer questions there. 

The current version of ANCOMBC is able to perform covariates adjustment and global tests (with more than 2 groups) as mentioned in this paper. The longitudinal analysis is currently not available, but we are drafting the paper about it. We will add the corresponding functions to the ANCOMBC package once the new paper gets published.

Stay tuned!

Huang
