### ISSUE TITLE
Publication for EM DA algorithm?

### ISSUE THREAD

**Issue by dadahan** [FrederickHuangLin/ANCOM-BC-Code-Archive#2]
Is there a pub for this implementation yet?

**Comment by dadahan** [comment]
Yes. https://www.nature.com/articles/s41467-020-17041-7

**Comment by FrederickHuangLin** [comment]
Thanks for your interest in ANCOM-BC. For your information, the corresponding R package can be found [here](https://github.com/FrederickHuangLin/ANCOMBC).

Best,

Huang
