### ISSUE TITLE
Disproportionate amount significant taxa, W = Inf, and se = 0

### ISSUE THREAD

**Issue by dadahan** [FrederickHuangLin/ANCOM-BC-Code-Archive#3]
In my dataset, most of the taxa are significant, with standard errors reported as 0 and W therefore reported as Inf. This is using all params the same as the tutorial . Different than the paper, I am running tests at the amplicon sequence variant (ASV) level rather than the phylum level. At first I thought group-specific ASVs that belong to few samples were being called structural zeros, causing a huge list of significant ASVs, but even after I tested the same analysis with `neg.lb = F` the problem persists. Any ideas?

**Comment by FrederickHuangLin** [comment]
Hi @dadahan,

Sorry for the huge delay in responding to your question.

It seems your dataset contains a lot of ASVs that are almost zeros, therefore, the algorithm would consider them as "structural zeros" and declares them as significant. 

Setting `zero.cut` to a lower value (say `zero.cut = 0.8`) will partial solve the problem. On the other hand, if "structural zeros" are not of your interest, you can simply skip them and check taxa with `W` statistics not equal to `Inf`.

For your information, this repository is for archive only, the corresponding ANCOMBC R package has been published in Bioconductor and is actively maintained [here](https://github.com/FrederickHuangLin/ANCOMBC).

Best,

Huang

**Comment by dadahan** [comment]
Thanks! Congrats on the BC pub.
