### ISSUE TITLE
Mix up in feature_table_pre_process(feature.table) documentation

### ISSUE THREAD

**Issue by NBaileyNCL** [FrederickHuangLin/ANCOM-BC-Code-Archive#5]
Very minor but just wanted to point this out as it confused me for a little bit.

In the documentation for feature_table_pre_process(), on the argument feature.table, it states:

"Data frame or matrix representing observed OTU table with samples in rows and OTUs (or taxa) in columns."

However in the original ANCOM, samples were in columns and taxa were in rows. I transposed my data, but the function threw an error:

Error in t(z) - e : non-conformable arrays

and looking into the source code I found the line:

sample.ID = colnames(feature.table)

which suggested to me columns were intended to be samples, as previously, and the function works great with the table the other way around. Just wanted to see if the documentation could be updated to avoid confusion

**Comment by FrederickHuangLin** [comment]
Hi @NBaileyNCL,

Sorry for the mistake and thanks for catching this!

The documentation has been updated!

Best,

Huang
