### ISSUE TITLE
Base of log for output mean difference in absolute abundance

### ISSUE THREAD

**Issue by NBaileyNCL** [FrederickHuangLin/ANCOM-BC-Code-Archive#6]
The documentation says the result is presented in a log scale, but does not state the base of the log

**Comment by FrederickHuangLin** [comment]
Hi @NBaileyNCL,

Thanks for pointing it out! It is natural log. The documentation has been updated accordingly!

For your information, this repository is for archive only, the corresponding ANCOMBC R package has been published in Bioconductor and is actively maintained [here](https://github.com/FrederickHuangLin/ANCOMBC).

Best,

Huang
