### ISSUE TITLE
OTU names in output table?

### ISSUE THREAD

**Issue by NBaileyNCL** [FrederickHuangLin/ANCOM-BC-Code-Archive#7]
I wondered if the OTU names could be included in the output table? At the moment ancom$res (output table) doesn't include a column with OTU names matching those in the input counts table.

I presume the output is returned in the same order i.e. row 1 in counts table corresponds to row one in the output table, but having the names included would be reassuring

Thanks

**Comment by FrederickHuangLin** [comment]
Hi @NBaileyNCL,

Sorry for missing your request! Currently, the ANCOM-BC model has been published on [Bioconductor](https://bioconductor.org/packages/release/bioc/html/ANCOMBC.html) and your concern has been addressed. For any future requests, please refer to the corresponding R package [repository](https://github.com/FrederickHuangLin/ANCOMBC).

Thank you,
Huang
